FROM --platform=linux/amd64 mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye

RUN npm install -g nodemon
# RUN npm install

#Give the path of your endpoint
# ENTRYPOINT ["nodemon", "/usr/src/app/server.js"]  
# CMD ["npm", "run", "dev"]